LAB_DESCRIPTION="Three routers and fifteen PCs using IPv4 static routing"
LAB_VERSION="1.0"

r1[0]="LAN1"
r1[1]="R1_R2"
r1[image]="kathara/core:latest"
r1[ipv6]="false"

r2[0]="LAN2"
r2[1]="R1_R2"
r2[2]="R2_R3"
r2[image]="kathara/core:latest"
r2[ipv6]="false"

r3[0]="LAN3"
r3[1]="R2_R3"
r3[image]="kathara/core:latest"
r3[ipv6]="false"

pc1_1[0]="LAN1"
pc1_1[image]="kathara/core:latest"
pc1_1[ipv6]="false"

pc1_2[0]="LAN1"
pc1_2[image]="kathara/core:latest"
pc1_2[ipv6]="false"

pc1_3[0]="LAN1"
pc1_3[image]="kathara/core:latest"
pc1_3[ipv6]="false"

pc1_4[0]="LAN1"
pc1_4[image]="kathara/core:latest"
pc1_4[ipv6]="false"

pc1_5[0]="LAN1"
pc1_5[image]="kathara/core:latest"
pc1_5[ipv6]="false"

pc2_1[0]="LAN2"
pc2_1[image]="kathara/core:latest"
pc2_1[ipv6]="false"

pc2_2[0]="LAN2"
pc2_2[image]="kathara/core:latest"
pc2_2[ipv6]="false"

pc2_3[0]="LAN2"
pc2_3[image]="kathara/core:latest"
pc2_3[ipv6]="false"

pc2_4[0]="LAN2"
pc2_4[image]="kathara/core:latest"
pc2_4[ipv6]="false"

pc2_5[0]="LAN2"
pc2_5[image]="kathara/core:latest"
pc2_5[ipv6]="false"

pc3_1[0]="LAN3"
pc3_1[image]="kathara/core:latest"
pc3_1[ipv6]="false"

pc3_2[0]="LAN3"
pc3_2[image]="kathara/core:latest"
pc3_2[ipv6]="false"

pc3_3[0]="LAN3"
pc3_3[image]="kathara/core:latest"
pc3_3[ipv6]="false"

pc3_4[0]="LAN3"
pc3_4[image]="kathara/core:latest"
pc3_4[ipv6]="false"

pc3_5[0]="LAN3"
pc3_5[image]="kathara/core:latest"
pc3_5[ipv6]="false"
