LAB_DESCRIPTION="Client-to-Apache HTTP lab with inline packet capture"
LAB_VERSION="1.0"
LAB_AUTHOR="A-Tesi"

client[0]="client_capture"
client[image]="kathara/core:latest"
client[ipv6]="false"

wireshark[0]="client_capture"
wireshark[1]="capture_server"
wireshark[image]="kathara/core:latest"
wireshark[ipv6]="false"

server[0]="capture_server"
server[image]="kathara/apache:latest"
server[ipv6]="false"
